

//register a new user
POST http://localhost:4000/users/
Content-Type: application/json


{
    "firstName":"dud",
    "lastName":"mizrahi",
    "email":"dddddd@admin.com",
    "password":"123456"
}

###
/// sign in 
POST http://localhost:4000/users/sign-in/
Content-Type: application/json


{
    "email":"admin@admin.com",
    "password":"$2b$10$nWtI0UsoxKO0Sv8.MaGbROdxEhgY37YIgT/OJp8O4EJ4MSEYRb6Ei"
}


###
//post a new review
POST http://localhost:4000/review/new-review
Content-Type: application/json


{
    "title":"far cry 6",
    "img":"fdsfdsfsdf",
    "body":"this is the body of ther game",
    "userId":"5f771a04c075f4f55aefded2"
}

###
//get all reviews
GET http://localhost:4000/review/

###
///get all revies by game title
GET http://localhost:4000/review/assassins creed valhalla


###
///get all reviews by user
GET http://localhost:4000/review/id/5f771a04c075f4f55aefded2



###
//signin user
POST http://localhost:4000/users/sign-in/
Content-Type: application/json


{
    "email":"galm44@gmail.com",
    "password":"123d45678"
}


###
//test token
POST http://localhost:4000/users/sign-in
Content-Type: application/json


{
    "email":"token@email.com",
    "password":"12345678"
}



###
//delete review
DELETE  http://localhost:4000/review/delete/5f7aa8f86f77be5b0eee810e
Content-Type: application/json


###
/// add to favorite
POST http://localhost:4000/review/favorite/5f817e1ad992791035389752
Content-Type: application/json


{
    "title":"far cry 6",
    "img":"fdsfdsfsdf",
    "body":"this is the body of ther game",
    "userId":"5f771a04c075f4f55aefded2"
}


###
///// get all favorites by user id
GET http://localhost:4000/review/favorite/5f817e1ad992791035389752


###
//remove from favorites
PUT http://localhost:4000/users/favorites/delete/5f7f4697e37653c015725c65
Content-Type: application/json


{
    "_id":"5f7b6ae13beaff526f82a3b1"
}


###
// add to favorite from User route
GET http://localhost:4000/users/favorite/5f7f4697e37653c015725c65


###
/// add to favorite from user route
PUT  http://localhost:4000/users/favorite/5f7f4697e37653c015725c65
Content-Type: application/json


{
    "title":"far cry 6",
    "img":"fdsfdsfsdf",
    "body":"this is the body of ther game",
    "userId":"5f771a04c075f4f55aefded2"
}


###
//get review by title
GET http://localhost:4000/review/as
Content-Type: application/json
